### ISSUE TITLE
Changing require to pig latin breaking tests

### ISSUE THREAD

**Issue by skitterm** [Esri/ember-esri-loader#34]
Using this addon and [ember-cli-code-coverage](https://github.com/kategengler/ember-cli-code-coverage) together causes tests run with the `coverage` option to fail. The error is `uncaught referenceError: require is not defined`.

After a couple hours, commented out and `yarn remove`'d `ember-esri-loader` from my app, re-ran tests with the `coverage` option, and everything worked. Note: Running tests without that `coverage` mumbo-jumbo worked fine with `ember-esri-loader` installed.

Perhaps it's because `ember-esri-loader` is redefining `require` statements?

Similar issues to mine (but with other libraries redefining `require`) [here](https://github.com/kategengler/ember-cli-code-coverage/issues/75).

**Comment by tomwayson** [comment]
@skitterm 

As we discussed this is due to [the `require()` statements that ember-cli-coverage injects into tests/index.html](https://github.com/kategengler/ember-cli-code-coverage/blob/7f9b961b0170580e67b7f60890b30254021ca1c6/lib/templates/test-body-footer.html#L6-L11).

I think we can solve this by adding `'tests/index.html'` to [the `files` array in index.js](https://github.com/Esri/ember-esri-loader/blob/ceb12ff86d452580c00a1b067aa0a142e39cfb43/index.js#L64-L69). I did some quick tests locally using the dummy app, and that seemed to work, but I did not try specifically using ember-cli-coverage. If this is still something you need to solve, would you mind trying that in your app (i.e. `npm link` to this addon)?

**Comment by skitterm** [comment]
I can give that a try. Though I didn't see the `tests/index.html` in that file you linked to. Would it be like the 5th entry below?

```javascript
files: [
        new RegExp(path.parse(outputPaths.app.js).name + '(.*js)'),
        new RegExp(path.parse(outputPaths.vendor.js).name + '(.*js)'),
        new RegExp(path.parse(outputPaths.tests.js).name + '(.*js)'),
        new RegExp(path.parse(outputPaths.testSupport.js.testSupport).name + '(.*js)'),
        new RegExp('tests/index.html') // added this line
      ],
```

**Comment by tomwayson** [comment]
Yeah,

You don't even need to make it a regEx. I tested w/ 

```js
files: [
        new RegExp(path.parse(outputPaths.app.js).name + '(.*js)'),
        new RegExp(path.parse(outputPaths.vendor.js).name + '(.*js)'),
        new RegExp(path.parse(outputPaths.tests.js).name + '(.*js)'),
        new RegExp(path.parse(outputPaths.testSupport.js.testSupport).name + '(.*js)'),
        tests/index.html' // this should work too
      ],
```

**Comment by skitterm** [comment]
That fixes it for me, thanks! Let me know when it's released.
